---
apiVersion: v1
kind: Template
labels:
  template: opendj-persistent-template
message: |-
  The following service(s) have been created in your project: ${OPENDJ_SERVICE_NAME}.

     Root user DN: ${OPENDJ_ROOT_USER_DN}
         Password: ${OPENDJ_ROOT_PASSWORD}
          Base DN: ${OPENDJ_BASE_DN}
   Connection URL: ldap://${OPENDJ_SERVICE_NAME}:1389/
    Master Server: ${OPENDJ_MASTER_SERVER}
    Secret Volume: ${OPENDJ_SECRET_VOLUME}

  For more information about using this template, including OpenShift considerations, see TODO: add urls.
metadata:
  annotations:
    description: |-
      OpenDJ is an LDAPv3 compliant directory service, which has been developed for the Java platform, providing a high performance, highly available, and secure store for the identities managed by your organization.
      For more information about using this template, including OpenShift considerations, see TODO: add urls.

      NOTE: Scaling to more than one replica is not supported. You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-sso
    openshift.io/display-name: OpenDJ
    openshift.io/documentation-url: TODO add documentation url
    openshift.io/long-description: This template provides a standalone OpenDJ
      server with a database created.  The database is stored on persistent storage.  The
      root DN, base DN, and password are chosen via parameters when provisioning
      this service.
    openshift.io/provider-display-name: Open Identity Platform Community.
    openshift.io/support-url: http://www.openidentityplatform.org
    tags: database,opendj,ldap
  name: opendj
objects:
#Secret
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-password: "{.data['opendj-root-password']}"
      template.openshift.io/expose-username: "{.data['opendj-root-user-dn']}"
    name: ${OPENDJ_SERVICE_NAME}
  labels:
    name: ${OPENDJ_SERVICE_NAME}
  stringData:
    opendj-root-password: ${OPENDJ_ROOT_PASSWORD}
    opend-root-user-dn: ${OPENDJ_ROOT_USER_DN}

#Service
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: ldap://{.spec.clusterIP}:{.spec.ports[?(.name=="opendj")].port}
    name: "${OPENDJ_SERVICE_NAME}"
    labels:
      name: ${OPENDJ_SERVICE_NAME}
  spec:
    ports:
    - name: 1389-tcp
      port: 1389
      protocol: TCP
      targetPort: 1389
    - name: 1636-tcp
      port: 1636
      protocol: TCP
      targetPort: 1636
    - name: 4444-tcp
      port: 4444
      protocol: TCP
      targetPort: 4444
    selector:
      name: "${OPENDJ_SERVICE_NAME}"
    sessionAffinity: None
    clusterIP: None
    type: ClusterIP
  status:
    loadBalancer: {}

#PersistentVolumeClaim
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${OPENDJ_SERVICE_NAME}"
    labels:
      name: ${OPENDJ_SERVICE_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${OPENDJ_SERVICE_NAME}
    labels:
      name: ${OPENDJ_SERVICE_NAME}
  spec: {}
  status:
    dockerImageRepository: ''

#BuildConfig
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${OPENDJ_SERVICE_NAME}
    labels:
      name: ${OPENDJ_SERVICE_NAME}
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
    source:
      type: Git
      git:
        uri: https://github.com/maximthomas/openidentityplatform-docker.git
      contextDir: 'opendj'
    strategy:
      type: Docker
      dockerStrategy:
        env:
          - name: BASE_DN
            value: ${OPENDJ_BASE_DN}
          - name: ROOT_USER_DN
            value: ${OPENDJ_ROOT_USER_DN}
          - name: ROOT_PASSWORD
            value: ${OPENDJ_ROOT_PASSWORD}
          - name: MASTER_SERVER
            value: ${OPENDJ_MASTER_SERVER}
          - name: SECRET_VOLUME
            value: ${OPENDJ_SECRET_VOLUME}
          - name: MYHOSTNAME
            value: ${OPENDJ_SERVICE_NAME}
    output:
      to:
        kind: ImageStreamTag
        name: ${OPENDJ_SERVICE_NAME}:latest
    resources: {}
  status:
    lastVersion: 0

#DeploymentConfig
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: "${OPENDJ_SERVICE_NAME}"
    labels:
      name: ${OPENDJ_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: "${OPENDJ_SERVICE_NAME}"
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: "${OPENDJ_SERVICE_NAME}"
      spec:
        containers:
        - capabilities: {}
          image: ""
          imagePullPolicy: IfNotPresent
          name: "${OPENDJ_SERVICE_NAME}"
          ports:
          - containerPort: 1389
            protocol: TCP
          - containerPort: 1636
            protocol: TCP
          - containerPort: 4444
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: "/opt/opendj/data"
            name: "${OPENDJ_SERVICE_NAME}-data"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: "${OPENDJ_SERVICE_NAME}-data"
          persistentVolumeClaim:
            claimName: "${OPENDJ_SERVICE_NAME}"
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${OPENDJ_SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${OPENDJ_SERVICE_NAME}:latest
        lastTriggeredImage: ''
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- description: The name of the OpenShift Service exposed for the database.
  displayName: Database Service Name
  name: OPENDJ_SERVICE_NAME
  required: true
  value: "opendj"
- description: DN for OpenDJ user that will be used for accessing the database.
  displayName: OpenDJ Root User DN
  name: OPENDJ_ROOT_USER_DN
  required: true
  value: "cn=Directory Manager"
- description: Password for the OpenDJ Root User.
  displayName: OpenDJ Connection Password
  from: "[a-zA-Z0-9]{16}"
  generate: expression
  name: OPENDJ_ROOT_PASSWORD
  required: true
- description: Name of the OpenDJ Base DN
  displayName: Base DN
  name: OPENDJ_BASE_DN
  required: true
  value: "dc=example,dc=com"
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: OpenDJ master server for replication.
  displayName: OpenDJ Master Server
  name: OPENDJ_MASTER_SERVER
  value:
  required: false
- description: Secret keystore volume.
  displayName: Secret Keystore Volume
  name: OPENDJ_SECRET_VOLUME
  value:
  required: false
